AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'node_modules/**/*'
    - 'ruby_gems/**/*'
    - 'test/**.rb'
    - 'tmp/**/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
