version: '3.6'
services:
  county-admin-web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /app/app
    ports:
      - ${COUNTY_ADMIN_APP_PORT}:3000
      - ${COUNTY_ADMIN_APP_WEBPACK_PORT}:3035
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    command: ['bundle', 'exec', 'rails', 'server']
  county-admin-test:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    volumes:
      - type: bind
        source: ./spec
        target: /app/spec
    environment:
      - SECRET_KEY_BASE
      - COUNTY_ADMIN_WEB_BASE_URL
