version: '3.2'
services:
  perry:
    image: cwds/perry
    hostname: perry
    depends_on:
          - cals_db2_data
          - postgresql_data
    restart: on-failure
    ports:
          - 18080:8080
          - 18081:8090
    env_file: .env
  cals_db2_data:
    image: cwds/db2data
    hostname: cals_db2_data
    ports:
      - ${DB_CMS_DB2_PORT}:50000
    env_file: .env

  postgresql_data:
    image: cwds/postgresql_data
    hostname: postgresql_data
    ports:
      - ${DB_POSTGRES_PORT}:${DB_POSTGRES_PORT}
    env_file: .env
  county-admin-web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /app/app
    ports:
      - ${COUNTY_ADMIN_APP_PORT}:3000
      - ${COUNTY_ADMIN_APP_WEBPACK_PORT}:3035
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      COUNTY_ADMIN_APP_JS_API_URL: ${COUNTY_ADMIN_APP_JS_API_URL}
      PERRY_API_BASE_URL: "http://${DEV_IP}:${PERRY_PORT}/perry"
      AUTHENTICATION: ${AUTHENTICATION}
      COUNTY_ADMIN_WEB_BASE_URL: ${COUNTY_ADMIN_WEB_BASE_URL}
      DASHBOARD_URL: ${DASHBOARD_URL}
    command: ['bundle', 'exec', 'rails', 'server']
    depends_on:
      - perry
  county-admin-test:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    volumes:
      - type: bind
        source: ./spec
        target: /app/spec
    environment:
      - SECRET_KEY_BASE
      - PERRY_API_BASE_URL
      - COUNTY_ADMIN_WEB_BASE_URL
      - DASHBOARD_URL
