version: '3.2'
services:
  perry:
    image: cwds/perry:3.0.4_828-RC
    hostname: perry
    depends_on:
          - cals_db2_data
          - postgresql_data
    restart: on-failure
    ports:
          - ${PERRY_PORT}:8080
          - 18081:8090
  cals_db2_data:
    image: cwds/db2data
    hostname: cals_db2_data
    ports:
      - ${DB_CMS_DB2_PORT}:50000
  postgresql_data:
    image: cwds/postgresql_data
    hostname: postgresql_data
    ports:
      - ${DB_POSTGRES_PORT}:${DB_POSTGRES_PORT}
  dora:
    image: cwds/dora:latest
    command: bash -c "./entrypoint.sh 2>&1 | tee 'log.file'"
    depends_on:
          - perry
          - elasticsearch
    ports:
          - ${DORA_PORT}:8080
    restart: on-failure
    healthcheck:
      test: head -n 500 log.file | grep "Started @"
      interval: 5s
      timeout: 10s
      retries: 80
  elasticsearch:
    image: cwds/elasticsearch_xpack_data:${ELASTICSEARCH_XPACK_DATA_VERSION}
    depends_on:
      - perry
    expose:
      - 9200
      - 9300
  county-admin-web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /app/app
    ports:
      - ${COUNTY_ADMIN_APP_PORT}:3000
      - ${COUNTY_ADMIN_APP_WEBPACK_PORT}:3035
    environment:
      BASE_SEARCH_API_URL: ${BASE_SEARCH_API_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      COUNTY_ADMIN_APP_JS_API_URL: ${COUNTY_ADMIN_APP_JS_API_URL}
      PERRY_API_BASE_URL: "http://${DEV_IP}:${PERRY_PORT}/perry"
      AUTHENTICATION: ${AUTHENTICATION}
      COUNTY_ADMIN_WEB_BASE_URL: ${COUNTY_ADMIN_WEB_BASE_URL}
      DASHBOARD_URL: ${DASHBOARD_URL}
      RAILS_RELATIVE_URL_ROOT: ${RAILS_RELATIVE_URL_ROOT}
    command: ['bundle', 'exec', 'rails', 'server']
    depends_on:
      - perry
  county-admin-test:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    volumes:
      - type: bind
        source: ./spec
        target: /app/spec
    environment:
      - SECRET_KEY_BASE
      - PERRY_API_BASE_URL
      - COUNTY_ADMIN_WEB_BASE_URL
      - DASHBOARD_URL
      - RAILS_RELATIVE_URL_ROOT
