development:
  features:
    authentication: <%= ENV.fetch('AUTHENTICATION', false) %>
test:
  features:
    authentication: <%= ENV.fetch('AUTHENTICATION', true) %>

production:
  features:
    authentication: <%= ENV.fetch('AUTHENTICATION', true) %>